#!/bin/sh
### BEGIN INIT INFO
# Provides:          teamspeak3
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop teamspeak3 server
# Description:       Start the teamspeak server
#  This script will start teamspeak3.
### END INIT INFO

case "$1" in
	start)
		sudo -u teamspeak /opt/teamspeak/teamspeak3-server_linux-amd64/ts3server_startscript.sh start
		;;
	stop)
		sudo -u teamspeak /opt/teamspeak/teamspeak3-server_linux-amd64/ts3server_startscript.sh stop
		;;
	status)
		sudo -u teamspeak /opt/teamspeak/teamspeak3-server_linux-amd64/ts3server_startscript.sh status
		;;
	restart)
		echo "Stopping teamspeak3"
		sudo -u teamspeak /opt/teamspeak/teamspeak3-server_linux-amd64/ts3server_startscript.sh stop
		echo "Starting teamspeak3"
		sudo -u teamspeak /opt/teamspeak/teamspeak3-server_linux-amd64/ts3server_startscript.sh start
		;;
esac

# vim: syntax=sh ts=4 sw=4 sts=4 sr noet
